---
title: "Untitled"
author: "Haziq Jamil"
date: "2023-05-12"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.path = "figure/", fig.width = 6.5, fig.height = 4.5, out.width = "100%", warning = FALSE)
library(tidyverse)
theme_set(theme_bw())
library(lavaan.bingof)
library(jcolors)
load("../vignettes/articles/simplots.RData")
```

# SRS Type I

```{r p_srs_type1_5}
p_srs_b
```

# SRS Power 

```{r p_srs_power_5}
p_srs_e
```

# Complex Type I

```{r p_complex_type1_5a}
complex_plot(res_complex_type1, alpha = 5, 
             exclude_sims = c("2F 10V", "3F 15V")) +
  coord_cartesian(ylim = c(0, 0.1))
```

# Complex Type I (cont.)

```{r p_complex_type1_5b}
complex_plot(res_complex_type1, alpha = 5, 
             exclude_sims = c("1F 5V", "1F 8V", "1F 15V")) +
  coord_cartesian(ylim = c(0, 0.1))
```

# Complex Power

```{r p_complex_power_5a}
complex_plot(res_complex_power, alpha = 5, 
             exclude_sims = c("2F 10V", "3F 15V"))
```

# Complex Power (cont.)

```{r p_complex_power_5b}
complex_plot(res_complex_power, alpha = 5, 
             exclude_sims = c("1F 5V", "1F 8V", "1F 15V"))
```
