---
output: 
  pdf_document:
    keep_tex: true
toc: true
title: "Tables of simulation results"
pkgdown:
  as_is: true
  extension: pdf
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE
)
options(knitr.kable.NA = "")
library(tidyverse)
theme_set(theme_bw())
library(kableExtra)
library(lavaan.bingof)
nn <- c(500, 1000, 2000, 3000)

colour_cells <- function(x, crit = crit10, alpha = 0.1) {
  where_colour <- !is.na(x) & (x + crit < alpha | x - crit > alpha)
  x <- as.character(formatC(x, digits = 3, format = "f"))
  x[grepl("na", x, ignore.case = TRUE)] <- ""
  cell_spec(x, color = ifelse(where_colour, "red", "black"))
}

fix_table <- function(x, nsim = res_srs_type1$n_sims[1],
                      highlight = TRUE) {
  crit10 <- 1.96 * sqrt(0.10 * 0.90 / nsim)
  crit5  <- 1.96 * sqrt(0.05 * 0.95 / nsim)
  crit1  <- 1.96 * sqrt(0.01 * 0.99 / nsim)
  
  if (isTRUE(highlight)) {
    x <- x %>%
      mutate(
        rej_rate10 = colour_cells(rej_rate10, crit10, 0.1),
        rej_rate5 = colour_cells(rej_rate5, crit5, 0.05),
        rej_rate1 = colour_cells(rej_rate1, crit1, 0.01),
      )
  } 
  x %>%
    rename(Name = name,
           `No. repl.` = n_sims,
           `Converged` = n_converged,
           `Rank def.` = n_rank_def,
           `10\\%` = rej_rate10,
           `5\\%` = rej_rate5,
           `1\\%` = rej_rate1)
}
```

Download the \LaTeX source from this [link](https://raw.githubusercontent.com/haziqj/lavaan.bingof/gh-pages/articles/sim_tables.tex).

## Simple random sampling

```{r, results = "asis"}
# Type I errors
for(the_n in nn) {
  cat(paste0("  \n### Type I errors ($n=",  the_n, "$)  \n"))
  tab <-
    res_srs_type1 %>% 
    filter(n == the_n) %>%
    arrange(n, sim, name) %>%
    select(sim, name, everything(), -n)
  fix_table(tab) %>%
    kbl(booktabs = TRUE, digits = 3, escape = FALSE, align = "lrrrrrrr") %>%
    kable_styling(latex_options = c("HOLD_position", "scale_down"),
                  font_size = 7) %>%
    add_header_above(c(" " = 5, "Rejection rate" = 3)) %>%
    collapse_rows(1:2, row_group_label_position = "stack", 
                  latex_hline = "major") %>%
    print()
  cat("  \n")
}

# Power 
for(the_n in nn) {
  cat(paste0("  \n### Power ($n=",  the_n, "$)  \n"))
  tab <-
    res_srs_power %>% 
    filter(n == the_n) %>%
    arrange(n, sim, name) %>%
    select(sim, name, everything(), -n)
  fix_table(tab, highlight = FALSE) %>%
    kbl(booktabs = TRUE, digits = 3, escape = FALSE, align = "lrrrrrrr") %>%
    kable_styling(latex_options = c("HOLD_position", "scale_down"),
                  font_size = 7) %>%
    add_header_above(c(" " = 5, "Rejection rate" = 3)) %>%
    collapse_rows(1:2, row_group_label_position = "stack", 
                  latex_hline = "major") %>%
    print()
  cat("  \n")
}
```

<!--Complex sampling results-->

```{r, results = "asis"}
samps <- c("Stratified", "Cluster", "Strat-clust")
# samps <- "Cluster"
for (the_samp in samps) {
  cat(paste0("  \n## ", the_samp, " sampling", "  \n"))
  
  # Type I errors
  for(the_n in nn) {
    cat(paste0("  \n### Type I errors ($n=",  the_n, "$)  \n"))
    tab <- 
      res_complex_type1 %>% 
      filter(n == the_n, sampling == the_samp) %>%
      arrange(n, sim, name) %>%
      select(sim, name, everything(), -n, -sampling)
    fix_table(tab) %>%
      select(-sim) %>%
      kbl(booktabs = TRUE, digits = 3, escape = FALSE, align = "lrrrrrr") %>%
      kable_styling(latex_options = c("HOLD_position", "scale_down"),
                    font_size = 7) %>%
      add_header_above(c(" " = 4, "Rejection rate" = 3)) %>%
      pack_rows(index = table(tab$sim)) %>%
      print()
    cat("  \n")
  }
  
  # Power 
  for(the_n in nn) {
    cat(paste0("  \n### Power ($n=",  the_n, "$)  \n"))
    tab <- 
      res_complex_power %>% 
      filter(n == the_n, sampling == the_samp) %>%
      arrange(n, sim, name) %>%
      select(sim, name, everything(), -n, -sampling)
    fix_table(tab, highlight = FALSE) %>%
      select(-sim) %>%
      kbl(booktabs = TRUE, digits = 3, escape = FALSE, align = "lrrrrrr") %>%
      kable_styling(latex_options = c("HOLD_position", "scale_down"),
                    font_size = 7) %>%
      add_header_above(c(" " = 4, "Rejection rate" = 3)) %>%
      pack_rows(index = table(tab$sim)) %>%
      print()
    cat("  \n")
  }
}
```
